from server_py import storage

DEFAULT_TAGS = [
    {"name": "Agreement Available in DMS", "description": "Whether the agreement document is available in the Document Management System. Return strictly 'Yes' or 'No'. If Yes and a DMS reference number or document ID is mentioned, append it after a hyphen (e.g., 'Yes - DMS/2024/001'). Do not guess — if availability is not explicitly stated, return 'Not mentioned'.", "category": "Compliance"},
    {"name": "Agreement End Date", "description": "The expiry or termination date of the agreement/lease. Extract the exact date as stated in the agreement — look in the preamble, recitals, term clause, or any amendment/addendum that extends the original term. Output MUST be in **dd/mm/yyyy** format (e.g., 31/03/2030) and MUST be an actual calendar date. **NEVER** return descriptive text like 'same as…', 'as above', 'refer to…', or any cross-reference — always resolve to the exact dd/mm/yyyy date even if it matches another field. If only month and year are given, use the last day of that month (e.g., 'March 2030' → 31/03/2030). If the agreement is perpetual or has no end date, return 'Perpetual'. If not stated anywhere, return 'Not mentioned'.", "category": "Dates"},
    {"name": "Agreement Party", "description": "All contracting parties to the agreement. List each party's full legal entity name exactly as it appears in the agreement (e.g., 'XYZ Telecom Private Limited' not just 'XYZ Telecom'). Include legal suffixes (Pvt. Ltd., LLC, Inc., LLP, etc.). If there are multiple parties, separate them with ' | ' (pipe with spaces). Identify each party's role if stated (e.g., 'Licensor: ABC Realty Pvt. Ltd. | Licensee: XYZ Telecom Ltd.'). Do not abbreviate or paraphrase entity names.", "category": "Legal"},
    {"name": "Agreement Start Date", "description": "The effective start or commencement date of the agreement/lease. Look in the preamble ('This agreement is made on…'), the execution clause, or the term/commencement clause. Output MUST be in **dd/mm/yyyy** format (e.g., 01/04/2020) and MUST be an actual calendar date. **NEVER** return descriptive text like 'same as…', 'as above', or any cross-reference — always resolve to the exact dd/mm/yyyy date even if it matches another field. If only month and year are given, use the first day of that month (e.g., 'April 2020' → 01/04/2020). If not stated anywhere, return 'Not mentioned'.", "category": "Dates"},
    {"name": "Area per Site", "description": "The area allocated per individual site as specified in the agreement, annexures, or schedules. Extract the numeric value and its unit of measurement exactly (e.g., '100 sq ft', '9.29 sq m'). If different sites have different areas, list each (e.g., 'Site A: 100 sq ft | Site B: 150 sq ft'). If area is given only as a total across all sites, return the total and note it (e.g., '500 sq ft (total for 5 sites)'). If not mentioned, return 'Not mentioned'.", "category": "Operational"},
    {"name": "Bank Details", "description": "Bank account details for rent/payment remittance as stated in the agreement or annexures. Extract all available details: beneficiary/account holder name, bank name, branch, account number, IFSC code (India) or SWIFT/BIC code (international), and account type if mentioned. Format as a structured string (e.g., 'Beneficiary: John Doe | Bank: SBI, MG Road Branch | A/C: 12345678 | IFSC: SBIN0001234'). If no bank details are mentioned, return 'Not mentioned'.", "category": "Financial"},
    {"name": "CAM Charges / Maintenance Charges", "description": "Common Area Maintenance (CAM) charges, maintenance fees, or service charges as specified in the agreement. Extract the exact amount with frequency (e.g., '₹5,000/month', 'Rs. 10 per sq ft per month'). Note whether CAM is included in rent or charged separately. If escalation terms for CAM exist, include them. If the tenant is responsible for all maintenance without specific charges, state 'Tenant responsible — no fixed CAM'. If not mentioned, return 'Not mentioned'.", "category": "Financial"},
    {"name": "Circle", "description": "The telecom circle, service area, or regional zone as mentioned in the agreement (e.g., 'Mumbai Circle', 'Tamil Nadu', 'Zone 3'). This is common in telecom lease agreements. If multiple circles apply, separate with ' | '. If not mentioned, return 'Not mentioned'.", "category": "Operational"},
    {"name": "City", "description": "The city or town where the leased property is located. Extract from the property address, premises description, or header of the agreement. Use the city name as written (e.g., 'Bengaluru' not 'Bangalore' if the document says 'Bengaluru'). If multiple cities are involved, list all separated by ' | '. If not mentioned, return 'Not mentioned'.", "category": "Location"},
    {"name": "Electricity / Energy Charge Rate (Per Unit)", "description": "The per-unit rate for electricity or energy charges as specified in the agreement. Extract the exact rate with units (e.g., '₹8.50 per unit', 'Rs. 12/kWh'). Note whether the rate is fixed or variable, and any escalation terms. If the tenant pays directly to the utility provider, state 'Direct to utility provider'. If electricity charges are included in rent or CAM, state that. If not mentioned, return 'Not mentioned'.", "category": "Financial"},
    {"name": "Escalation %", "description": "The annual rent escalation percentage or terms. Extract the exact percentage (e.g., '5%', '10% every 3 years', '15% after 11 months'). If escalation is based on a formula or index (e.g., CPI, WPI), state the formula. If different escalation rates apply to different periods, list all (e.g., '5% for years 1-3, 10% for years 4-5'). If no escalation is mentioned, return 'No escalation'. If not mentioned, return 'Not mentioned'.", "category": "Financial"},
    {"name": "Escalation Start Date", "description": "The date from which rent escalation becomes effective. Output MUST be in dd/mm/yyyy format. If escalation starts after a fixed period (e.g., 'after 11 months'), calculate the actual date from the agreement start date if possible. If escalation is annual from the start, state the first escalation date. If not mentioned, return 'Not mentioned'.", "category": "Dates"},
    {"name": "Flat / Unit Number", "description": "The specific flat number, unit number, office number, or suite identifier of the leased premises (e.g., 'Flat No. 302', 'Unit 5A', 'Office #1201', 'Shop No. G-15'). Look in the premises description, schedule of premises, or address section. If multiple units are leased, list all separated by ' | '. If not mentioned, return 'Not mentioned'.", "category": "Location"},
    {"name": "Interest on Security Deposit", "description": "The interest rate payable on the security deposit, if any. Extract the rate and terms (e.g., '9% per annum simple interest', 'SBI FD rate minus 1%'). Note whether interest is payable periodically or at the end of the lease term. If the deposit is interest-free, state 'Interest-free'. If not mentioned, return 'Not mentioned'.", "category": "Financial"},
    {"name": "Landlord Address", "description": "The full address of the landlord/lessor/licensor as stated in the agreement. Include all components: building/house name or number, street, locality/area, city, state, PIN/ZIP code. Extract exactly as written without reformatting. If multiple landlords have different addresses, list each with the landlord's name. If not mentioned, return 'Not mentioned'.", "category": "Location"},
    {"name": "Lock-in Period", "description": "The lock-in period during which the lease cannot be terminated by either or both parties. Extract the duration (e.g., '3 years', '36 months') and specify who it applies to (e.g., 'Both parties', 'Tenant only', 'Landlord only'). Note the consequences of breaking the lock-in if stated (e.g., 'Penalty of 3 months rent'). If there is no lock-in period, return 'No lock-in'. If not mentioned, return 'Not mentioned'.", "category": "Terms"},
    {"name": "Monthly Rental Amount", "description": "The monthly rent or license fee amount. Extract ONLY the numeric value without currency symbols (e.g., '50000' not '₹50,000'). If rent varies by period (e.g., different amounts for different years), extract the initial/current rent and note the schedule (e.g., '50000 (Year 1), 55000 (Year 2)'). If rent is stated annually, divide by 12 and note it. If GST/tax is mentioned separately, exclude it from the base rent. If not mentioned, return 'Not mentioned'.", "category": "Financial"},
    {"name": "Nature of Agreement", "description": "The type or nature of the agreement (e.g., 'Lease Deed', 'License Agreement', 'Leave and License', 'Rent Agreement', 'Sub-Lease', 'Deed of Lease', 'Tenancy Agreement', 'MOU', 'LOI'). Extract the exact title or description as stated in the agreement header or preamble. If the document is an amendment/addendum/renewal, state that (e.g., 'Renewal of Lease Deed'). If not mentioned, return 'Not mentioned'.", "category": "Legal"},
    {"name": "Notice Period", "description": "The advance notice period required for termination or non-renewal of the agreement. Extract the duration (e.g., '3 months', '90 days', '6 months') and specify who must give notice (e.g., 'Either party', 'Tenant', 'Landlord'). If different notice periods apply to different parties or circumstances, list all. If there is no notice period requirement, return 'No notice period'. If not mentioned, return 'Not mentioned'.", "category": "Terms"},
    {"name": "Property Address", "description": "The complete address of the leased/licensed property or premises. Include ALL components: building/tower name, floor number, flat/unit number, street/road name, area/locality, landmark (if any), city, district, state, and PIN/ZIP code. Extract exactly as written in the agreement, typically found in the premises description, Schedule A/B, or the first recital. If premises span multiple addresses, list all separated by ' | '. If not mentioned, return 'Not mentioned'.", "category": "Location"},
    {"name": "Rent Start Date", "description": "The date from which rent becomes payable as per the agreement. This may differ from the agreement start date (e.g., after a rent-free/FOC period). Output MUST be in dd/mm/yyyy format (e.g., 01/07/2020). Look in the rent commencement clause, payment terms, or any handover/possession-related provisions. If only month and year are given, use the first day of that month. If rent starts from the agreement start date and no separate rent start date is mentioned, still extract and state that date. If not mentioned, return 'Not mentioned'.", "category": "Dates"},
    {"name": "Rental Hold / FOC Period", "description": "Any rent-free, Free of Cost (FOC), or rental hold period granted under the agreement. Extract the duration (e.g., '6 months', '90 days'), the start reference point (e.g., 'from date of handover', 'from agreement execution date'), and any conditions or limitations. If the entire lease is FOC, state 'Entire lease term is FOC'. If there is no rent-free period, return 'None'. If not mentioned, return 'Not mentioned'.", "category": "Financial"},
    {"name": "Security Deposit Amount", "description": "The security deposit amount payable or paid as per the agreement. Extract ONLY the numeric value without currency symbols (e.g., '500000' not '₹5,00,000'). Note whether it is refundable or non-refundable, and any conditions for forfeiture or return. If paid in installments, note the schedule. If a bank guarantee is required instead of or in addition to cash deposit, state that. If not mentioned, return 'Not mentioned'.", "category": "Financial"},
    {"name": "Sites Built Count", "description": "The number of sites actually built or constructed as documented in project records, completion certificates, or lease documentation. Extract the exact count as a number (e.g., '5'). If the count differs between planned and actual, capture the actual built count and note the planned count separately (e.g., 'Built: 3 | Planned: 5'). If not mentioned, return 'Not mentioned'.", "category": "Operational"},
    {"name": "Total Area Acquired", "description": "The total area acquired or leased as specified in the agreement, including all sites combined. Extract the numeric value with its unit of measurement (e.g., '5000 sq ft', '464.5 sq m'). If stated in multiple units, capture the primary one used in the agreement. If the area was amended or revised, capture the latest figure. If not mentioned, return 'Not mentioned'.", "category": "Operational"},
    {"name": "Total Sites Acquired from Institution", "description": "The total count of sites acquired from the institution/landlord as mentioned in the agreement, schedules, or supporting documents. Extract as a plain number (e.g., '10'). If the count changed over time due to additions or surrenders, capture the latest count and note the original (e.g., 'Current: 8 | Originally: 10'). If not mentioned, return 'Not mentioned'.", "category": "Operational"},
]


def seed_database():
    try:
        existing_tags = storage.get_tags()
        if len(existing_tags) == 0:
            print("Seeding database with default tags...")
            for tag in DEFAULT_TAGS:
                try:
                    storage.create_tag(tag["name"], tag.get("description"), tag.get("category"))
                except Exception:
                    pass
            print(f"Seeded {len(DEFAULT_TAGS)} default tags")
    except Exception as e:
        print(f"Error seeding database: {e}")
